services:
  backend:
    build: .
    container_name: dockerman-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /Users/iliastaboada/.docker/run/docker.sock:/var/run/docker.sock
    environment:
      - SOCKET_PATH=/var/run/docker.sock
    restart: unless-stopped
